theme: jekyll-theme-minimal

github: is\_project\_page:false
title: <mytitle>

include:
  - _pages
  
defaults: 
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.
