project:
  type: website
  output-dir: docs

website:
  title: "DCE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cdc.qmd
      - matheco.qmd
      - cv.qmd
      - contact.qmd
    right:
      - icon: github
        href: "https://github.com/David-Elzinga"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



